#
# partcad-bosl2, 2026
#
# Licensed under Apache License, Version 2.0.
#
"""A PartCAD ``basic`` repository plugin that serves BOSL2 as PartCAD parts.

BOSL2 (the Belfry OpenSCAD Library v2, BSD-2-Clause) is a large collection of
parametric OpenSCAD modules. This plugin exposes those modules as PartCAD
``scad`` parts *without vendoring* the library: the BOSL2 source is downloaded
on demand into a local cache the first time a part is listed or built, and each
part is generated by parsing a module's signature straight from that source.

PartCAD runs this script once per data request (via ``runpy``) with the request
in the global ``request`` and ``__name__`` set to the API ("get"); the answer is
returned in the global ``output`` as ``{"result": <value>}``. See the
"Repositories" section of the PartCAD documentation for the key conventions.

Each of the categories in :data:`CATEGORIES` is imported (in ``partcad.yaml``) as
a separate ``external`` package with its own ``subfolder``, so every key this
script sees is scoped, e.g. ``shapes3d/objects/part`` or
``gears/files/_bosl2_gears.scad``.

The module is import-safe (defines only functions and data at import time), so
the pure signature-parsing logic is unit-tested directly; see
``test_bosl2_repo.py``.
"""

import base64
import io
import os
import re
import shutil
import tarfile
import urllib.request

# ---------------------------------------------------------------------------
# What BOSL2 to fetch, and how it is laid out.
# ---------------------------------------------------------------------------

DEFAULT_REF = "v2.0.747"
_TARBALL_URL = "https://github.com/BelfrySCAD/BOSL2/archive/refs/tags/%s.tar.gz"

# The BOSL2 source files we generate parts from, keyed by the category (and
# PartCAD sub-package) name. Only files that yield renderable 3D solids are
# listed; 2D, helper and mask-only files are intentionally excluded.
CATEGORIES = {
    "shapes3d": "shapes3d.scad",
    "gears": "gears.scad",
    "threading": "threading.scad",
    "screws": "screws.scad",
    "metric_screws": "metric_screws.scad",
    "nema_steppers": "nema_steppers.scad",
    "ball_bearings": "ball_bearings.scad",
    "linear_bearings": "linear_bearings.scad",
    "joiners": "joiners.scad",
    "cubetruss": "cubetruss.scad",
    "bottlecaps": "bottlecaps.scad",
    "walls": "walls.scad",
}

# The files that ``std.scad`` already pulls in. A part whose category is one of
# these only needs ``include <std.scad>``; anything else also needs its own file
# included (after std, which BOSL2's component files rely on for constants).
STD_INCLUDED = {
    "version",
    "constants",
    "transforms",
    "distributors",
    "miscellaneous",
    "color",
    "attachments",
    "beziers",
    "shapes3d",
    "shapes2d",
    "drawing",
    "masks",
    "math",
    "paths",
    "lists",
    "comparisons",
    "linalg",
    "trigonometry",
    "vectors",
    "affine",
    "coords",
    "geometry",
    "regions",
    "strings",
    "vnf",
    "structs",
    "rounding",
    "skin",
    "utility",
    "partitions",
}


# ===========================================================================
# Signature parsing (pure)
# ===========================================================================


def strip_comments(text):
    """Remove block and line comments so they cannot break argument splitting."""
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"(?m)//.*$", "", text)
    return text


def _matching_paren(text, open_idx):
    """Index of the ``)`` matching the ``(`` at ``open_idx`` (quote-aware)."""
    depth = 0
    quote = None
    for i in range(open_idx, len(text)):
        ch = text[i]
        if quote:
            if ch == quote:
                quote = None
        elif ch in "\"'":
            quote = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return i
    return -1


def find_modules(text):
    """Return ``[(name, arg_string), ...]`` for top-level ``module NAME(...)``."""
    out = []
    for m in re.finditer(r"(?m)^module\s+([A-Za-z_]\w*)\s*\(", text):
        open_idx = m.end() - 1
        close_idx = _matching_paren(text, open_idx)
        if close_idx != -1:
            out.append((m.group(1), text[open_idx + 1 : close_idx]))
    return out


def split_args(arg_string):
    """Split an argument list on its top-level commas."""
    args = []
    depth = 0
    quote = None
    cur = ""
    for ch in arg_string:
        if quote:
            cur += ch
            if ch == quote:
                quote = None
        elif ch in "\"'":
            quote = ch
            cur += ch
        elif ch in "([{":
            depth += 1
            cur += ch
        elif ch in ")]}":
            depth -= 1
            cur += ch
        elif ch == "," and depth == 0:
            args.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        args.append(cur)
    return [a.strip() for a in args if a.strip()]


def split_name_default(arg):
    """Split ``name = default`` on the first top-level ``=``.

    Returns ``(name, default_or_None)``; a bare argument (no ``=``) is ``undef``
    in OpenSCAD, i.e. optional, and yields ``None``.
    """
    depth = 0
    quote = None
    for i, ch in enumerate(arg):
        if quote:
            if ch == quote:
                quote = None
        elif ch in "\"'":
            quote = ch
        elif ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        elif ch == "=" and depth == 0:
            return arg[:i].strip(), arg[i + 1 :].strip()
    return arg.strip(), None


def classify_scalar(default):
    """Return ``(type, value)`` for a simple scalar default, else ``None``.

    Vectors, expressions and ``undef`` return ``None`` so the argument is left
    at the BOSL2 default rather than being exposed as a PartCAD parameter.
    """
    if default is None:
        return None
    d = default.strip()
    if d == "" or d == "undef":
        return None
    if d in ("true", "false"):
        return ("bool", d == "true")
    if re.fullmatch(r"[+-]?\d+", d):
        return ("int", int(d))
    if re.fullmatch(r"[+-]?(\d+\.\d*|\.\d+|\d+)([eE][+-]?\d+)?", d) and re.search(r"[.eE]", d):
        try:
            return ("float", float(d))
        except ValueError:
            return None
    if len(d) >= 2 and d[0] == '"' and d[-1] == '"':
        return ("string", d[1:-1])
    return None


# ===========================================================================
# Part synthesis (pure)
# ===========================================================================

# Attachable / render-control arguments every BOSL2 shape shares; never exposed
# and never set (BOSL2's own defaults are correct).
EXCLUDE = {
    "anchor",
    "spin",
    "orient",
    "atype",
    "cp",
    "p",
    "p1",
    "p2",
    "edges",
    "except",
    "except_edges",
    "children",
    "convexity",
    "center",
    "realign",
    "style",
    "tex_style",
}

# Names of every radius/diameter/tube dimension we reason about as one family.
_RADIUS_FAMILY = {
    "r",
    "d",
    "r1",
    "r2",
    "d1",
    "d2",
    "r_maj",
    "r_min",
    "d_maj",
    "d_min",
    "or",
    "ir",
    "od",
    "id",
    "wall",
    "or1",
    "or2",
    "od1",
    "od2",
    "ir1",
    "ir2",
    "id1",
    "id2",
}
_LENGTH_NAMES = {"h", "l", "length", "height"}
_SIZE_NAMES = {"size", "size1", "size2"}

# Domain-specific required arguments the geometric resolver cannot infer, keyed
# by module. This is data, not per-part configuration: the engine still extracts
# every scalar-defaulted argument around these.
SEED = {
    "spur_gear": {"teeth": ("int", 20), "circ_pitch": ("float", 5.0), "thickness": ("float", 8.0)},
    "ring_gear": {"teeth": ("int", 32), "circ_pitch": ("float", 5.0), "thickness": ("float", 8.0)},
    "rack": {"teeth": ("int", 8), "circ_pitch": ("float", 5.0), "thickness": ("float", 8.0), "height": ("float", 10.0)},
    "bevel_gear": {
        "teeth": ("int", 20),
        "circ_pitch": ("float", 5.0),
        "face_width": ("float", 8.0),
        "mate_teeth": ("int", 20),
    },
    "worm": {"circ_pitch": ("float", 5.0), "d": ("float", 30.0), "starts": ("int", 1)},
    "worm_gear": {"circ_pitch": ("float", 5.0), "teeth": ("int", 30), "worm_diam": ("float", 30.0)},
    "threaded_rod": {"d": ("float", 12.0), "l": ("float", 30.0), "pitch": ("float", 2.0)},
    "threaded_nut": {"nutwidth": ("float", 18.0), "id": ("float", 12.0), "h": ("float", 10.0), "pitch": ("float", 2.0)},
    "trapezoidal_threaded_rod": {"d": ("float", 12.0), "l": ("float", 30.0), "pitch": ("float", 2.0)},
    "acme_threaded_rod": {"d": ("float", 12.0), "l": ("float", 30.0), "pitch": ("float", 2.0)},
    "buttress_threaded_rod": {"d": ("float", 12.0), "l": ("float", 30.0), "pitch": ("float", 2.0)},
    "square_threaded_rod": {"d": ("float", 12.0), "l": ("float", 30.0), "pitch": ("float", 2.0)},
    "screw": {"spec": ("string", "M8"), "length": ("float", 20.0)},
    "screw_hole": {"spec": ("string", "M8"), "length": ("float", 20.0)},
    "ball_bearing": {"trade_size": ("string", "608")},
    "nema_stepper_motor": {"size": ("int", 17), "h": ("float", 24.0)},
    "linear_bearing": {"trade_size": ("string", "LM8UU")},
    "snap_pin": {"size": ("string", "standard")},
    "snap_pin_socket": {"size": ("string", "standard")},
}

# Modules that never render a standalone solid, filtered out wholesale.
_BLOCKLIST = {
    # empty / non-3D / text geometry
    "text3d",
    "path_text",
    "ruler",
    "heightfield",
    "cylindrical_heightfield",
    "plot_revolution",
    "textured_tile",
    "regular_prism",
    # need data/paths/regions or exotic required specs the engine cannot supply
    "rect_tube",
    "interior_fillet",
    "thread_helix",
    "ball_screw_rod",
    "generic_threaded_rod",
    "generic_threaded_nut",
    "npt_threaded_rod",
    "bspp_threaded_rod",
    "modular_hose",
    "regular_polyhedron",
    "rabbit_clip",
    "hirth",
    "dovetail",
    "knuckle_hinge",
    "generic_bottle_cap",
    "enveloping_worm",
    "nut_trap_inline",
    "shoulder_screw",
    "hex_panel",
    "trapezoidal_threaded_nut",
    "acme_threaded_nut",
    "buttress_threaded_nut",
    "square_threaded_nut",
    "pco1810_cap",
}


def skip_module(name):
    """True for modules that never render a standalone solid."""
    if name.startswith("_"):
        return True  # private helper
    if name.endswith("2d"):
        return True  # 2D geometry, cannot be exported as a mesh
    if name.endswith("_mask"):
        return True  # boolean-subtraction masks
    return name in _BLOCKLIST


def resolve_dimensions(names):
    """Pick a conflict-free set of dimension arguments for a module.

    BOSL2 exposes the same dimension through mutually exclusive aliases
    (``r``/``d``/``r1``+``r2``, ``h``/``l``/``length``/``height``,
    ``size``/``size1``+``size2``). Setting more than one alias trips a "define
    exactly one of ..." assertion, so we choose a single canonical spelling per
    family and mark the rest to be skipped.
    """
    chosen = {}
    skip = set()

    length = [n for n in ("h", "l", "length", "height") if n in names]
    if length:
        chosen[length[0]] = ("float", 20.0)
        skip.update(length[1:])

    if "r" in names:
        chosen["r"] = ("float", 10.0)
    elif "d" in names:
        chosen["d"] = ("float", 20.0)
    elif "r1" in names and "r2" in names:
        chosen["r1"] = ("float", 10.0)
        chosen["r2"] = ("float", 6.0)
    elif "d1" in names and "d2" in names:
        chosen["d1"] = ("float", 20.0)
        chosen["d2"] = ("float", 12.0)
    elif "r_maj" in names and "r_min" in names:
        chosen["r_maj"] = ("float", 15.0)
        chosen["r_min"] = ("float", 4.0)
    elif "d_maj" in names and "d_min" in names:
        chosen["d_maj"] = ("float", 30.0)
        chosen["d_min"] = ("float", 8.0)
    elif "od" in names and "id" in names:
        chosen["od"] = ("float", 20.0)
        chosen["id"] = ("float", 12.0)
    elif "or" in names and "ir" in names:
        chosen["or"] = ("float", 10.0)
        chosen["ir"] = ("float", 6.0)
    skip.update(_RADIUS_FAMILY - set(chosen))

    if "size" in names:
        chosen["size"] = ("float", 20.0)
        skip.update({"size1", "size2"})
    elif "size1" in names and "size2" in names:
        chosen["size1"] = ("float", 20.0)
        chosen["size2"] = ("float", 10.0)

    return chosen, skip


def _prune_chosen_for_seed(chosen, seed):
    """Drop resolver picks whose dimension family the seed already covers."""
    seedkeys = set(seed)
    for family in (_LENGTH_NAMES, _RADIUS_FAMILY, _SIZE_NAMES):
        if seedkeys & family:
            for k in [k for k in chosen if k in family]:
                del chosen[k]
    return chosen


def synth_part(module, arg_string, category, wrapper_name):
    """Build a PartCAD part config for a module, or ``None`` if not renderable."""
    if skip_module(module):
        return None

    names = []
    defaults = {}
    for arg in split_args(arg_string):
        name, default = split_name_default(arg)
        if not re.fullmatch(r"[A-Za-z_]\w*", name or ""):
            continue
        names.append(name)
        defaults[name] = default
    nameset = set(names)

    chosen, skip = resolve_dimensions(nameset)
    seed = SEED.get(module, {})
    _prune_chosen_for_seed(chosen, seed)

    params = {}
    bare_unset = 0
    for name in names:
        if name in EXCLUDE or name.startswith("$") or name.startswith("_"):
            continue
        if name in seed:
            params[name] = {"type": seed[name][0], "default": seed[name][1]}
            continue
        if name in chosen:
            params[name] = {"type": chosen[name][0], "default": chosen[name][1]}
            continue
        if name in skip:
            continue
        scalar = classify_scalar(defaults[name])
        if scalar is not None:
            params[name] = {"type": scalar[0], "default": scalar[1]}
        elif defaults[name] is None:
            bare_unset += 1

    # Skip modules that set no geometry yet still have unfilled inputs: helpers,
    # masks and children-consumers that would not render on their own.
    if not chosen and module not in SEED and bare_unset:
        return None

    return {
        "type": "scad",
        "path": wrapper_name,
        "method": module,
        "desc": "BOSL2 %s() from %s.scad" % (module, category),
        "parameters": params,
    }


# ===========================================================================
# BOSL2 source: fetched on demand into a local cache.
# ===========================================================================


def wrapper_name(category):
    """The (per-category, unique) name of the throwaway include wrapper."""
    return "_bosl2_%s.scad" % category


def _cache_root():
    override = os.environ.get("PARTCAD_BOSL2_CACHE")
    if override:
        return override
    xdg = os.environ.get("XDG_CACHE_HOME")
    base = xdg if xdg else os.path.join(os.path.expanduser("~"), ".cache")
    return os.path.join(base, "partcad-bosl2")


def _download_and_extract(url, dest):
    """Download the BOSL2 tarball and extract it into ``dest`` (top dir stripped)."""
    os.makedirs(dest, exist_ok=True)
    with urllib.request.urlopen(url, timeout=120) as resp:
        data = resp.read()
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tf:
        for member in tf.getmembers():
            parts = member.name.split("/", 1)
            if len(parts) < 2 or not parts[1]:
                continue  # the top-level 'BOSL2-<ref>/' entry itself
            rel = parts[1]
            if os.path.isabs(rel) or ".." in rel.split("/"):
                continue  # defensive: never escape 'dest'
            member.name = rel
            tf.extract(member, dest)


def ensure_bosl2(ref):
    """Return the local directory holding BOSL2 ``ref``, downloading if needed.

    The download is idempotent (guarded by a ``std.scad`` marker) and offline
    tolerant: if the network is unavailable but the version is already cached,
    the cache is used.
    """
    base = _cache_root()
    dest = os.path.join(base, ref)
    marker = os.path.join(dest, "std.scad")
    if os.path.exists(marker):
        return dest

    os.makedirs(base, exist_ok=True)
    tmp = "%s.tmp-%d" % (dest, os.getpid())
    try:
        _download_and_extract(_TARBALL_URL % ref, tmp)
    except Exception:
        shutil.rmtree(tmp, ignore_errors=True)
        if os.path.exists(marker):  # offline, but already cached
            return dest
        raise
    try:
        os.replace(tmp, dest)  # publish atomically
    except OSError:
        # A concurrent build won the race; discard our copy and use theirs.
        shutil.rmtree(tmp, ignore_errors=True)
    return dest


def catalog_for(category, cache_dir):
    """Parse a category's BOSL2 source into ``{part_name: config}``."""
    src = os.path.join(cache_dir, CATEGORIES[category])
    if not os.path.exists(src):
        return {}
    with open(src, encoding="utf-8") as f:
        text = strip_comments(f.read())
    wname = wrapper_name(category)
    parts = {}
    for module, arg_string in find_modules(text):
        config = synth_part(module, arg_string, category, wname)
        if config is not None:
            parts[module] = config
    return parts


def wrapper_scad(cache_dir, category):
    """The include wrapper every part in ``category`` renders against.

    Absolute includes are used so the wrapper resolves regardless of the
    directory PartCAD renders it from (it renders a throwaway copy of the file
    with the module call appended). BOSL2's component files rely on ``std.scad``
    for their constants, so ``std.scad`` is always included first.
    """
    lines = [
        "// Generated by partcad-bosl2. Includes the Belfry OpenSCAD Library v2",
        "// (BSD-2-Clause), fetched on demand into a local cache.",
        "include <%s>" % os.path.join(cache_dir, "std.scad"),
    ]
    if category not in STD_INCLUDED:
        lines.append("include <%s>" % os.path.join(cache_dir, CATEGORIES[category]))
    return "\n".join(lines) + "\n"


# ===========================================================================
# The key/value repository protocol.
# ===========================================================================


def _requested_ref():
    """The BOSL2 ref the repository was configured with (``ref`` parameter)."""
    req = globals().get("request") or {}
    return (req.get("parameters") or {}).get("ref") or DEFAULT_REF


def get(key):
    """Answer one key/value repository request. See the module docstring."""
    category, _, sub = key.partition("/")
    if category not in CATEGORIES:
        # A top-level (unscoped) request. The root package is a normal local
        # package; the plugin only serves the per-category sub-packages.
        return None

    if sub == "deps":
        return []  # categories are leaves: no further children
    if sub == "meta":
        return {"desc": "BOSL2 %s modules as parametric OpenSCAD parts." % category}

    if sub == "objects/part":
        return catalog_for(category, ensure_bosl2(_requested_ref()))
    if sub.startswith("objects/part/"):
        name = sub[len("objects/part/") :]
        return catalog_for(category, ensure_bosl2(_requested_ref())).get(name)
    if sub.startswith("objects/"):
        return {}  # sketches, assemblies, interfaces, ...: none

    if sub.startswith("files/"):
        fname = sub[len("files/") :]
        if fname != wrapper_name(category):
            return None
        content = wrapper_scad(ensure_bosl2(_requested_ref()), category)
        return base64.b64encode(content.encode()).decode()

    return None


# The runpy entry point used by PartCAD (``__name__`` is the API name).
if __name__ == "get":
    output = {"result": get(request["key"])}  # noqa: F821 - injected by the runtime
elif __name__ == "__main__":
    # Local debugging: summarize the generated catalog.
    _cache = ensure_bosl2(DEFAULT_REF)
    _total = 0
    for _cat in CATEGORIES:
        _parts = catalog_for(_cat, _cache)
        _total += len(_parts)
        print("%-16s %2d parts: %s" % (_cat, len(_parts), ", ".join(sorted(_parts))))
    print("\nTotal: %d parts across %d categories" % (_total, len(CATEGORIES)))
else:
    output = {}
